from __future__ import annotations

import json
import logging
from typing import Any

from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from omai.clients.database_schema_client import (
    DatabaseSchemaClient,
    DatabaseSchemaClientError,
)


logger = logging.getLogger(__name__)


class DraftOperationalSqlInput(BaseModel):
    """Arguments for the draft-only operational SQL tool.

    The SQL text is generated by the model and echoed back with schema context.
    It is not validated or executed in step 2.
    """

    question: str = Field(
        description="The user's operational question that the SQL draft is meant to answer."
    )
    sql: str = Field(
        description=(
            "A proposed read-only SELECT query. This tool only records and returns "
            "the draft; it does not execute SQL."
        )
    )
    notes: str | None = Field(
        default=None,
        description="Optional explanation of assumptions, joins, or expected output.",
    )


def _json_result(value: Any) -> str:
    """Serialize tool output compactly for the model."""
    return json.dumps(value, default=str, separators=(",", ":"))


def build_database_schema_tools(
    client: DatabaseSchemaClient,
    site_id: int,
) -> list[StructuredTool]:
    """Build tools that expose curated schema context without executing SQL.

    Step 2 intentionally stops at SQL drafting. The returned LangChain tool can
    help the model propose a query shape, but no database connection is opened
    and no query is run.
    """

    def draft_operational_sql(
        question: str,
        sql: str,
        notes: str | None = None,
    ) -> str:
        """Return a non-executed SQL draft using the curated operational schema."""
        logger.info("Drafting non-executed operational SQL site_id=%s", site_id)
        try:
            # Load the allowlisted schema at invocation time so edits to the
            # markdown are picked up without rebuilding the Python package.
            schema = client.load_schema()
            # Echo the drafted SQL with explicit executed=false metadata. Later
            # steps can add validation/execution, but this tool must stay inert.
            return _json_result(
                {
                    "ok": True,
                    "executed": False,
                    "site_id": site_id,
                    "question": question,
                    "sql": sql,
                    "notes": notes,
                    "schema": schema,
                    "warning": (
                        "This SQL was not executed. It is only a draft and must be "
                        "validated before any future execution tool can run it."
                    ),
                }
            )
        except DatabaseSchemaClientError as exc:
            # Return a structured tool error so the assistant can explain that
            # schema context is unavailable instead of failing the chat request.
            logger.warning("Database schema lookup failed: %s", exc)
            return _json_result({"ok": False, "executed": False, "error": str(exc)})

    return [
        # Register one draft-only tool. It is intentionally separate from future
        # validators/executors so each step can be reviewed independently.
        StructuredTool.from_function(
            func=draft_operational_sql,
            name="draft_operational_sql",
            description=(
                "Draft a read-only SQL query for ad hoc Ometrics operational data "
                "questions that existing report, reading, shutdown, timeline, "
                "capability, or RAG tools cannot answer well. This tool does not "
                "execute SQL and does not connect to the database. The SQL must be "
                "a SELECT query scoped to the selected site_id."
            ),
            args_schema=DraftOperationalSqlInput,
        )
    ]
